//! Benchmark entry registration system.
//!
//! Benchmarks register themselves at pre-main init time by pushing
//! [`AnyBenchEntry`] nodes into the global [`BENCH_ENTRIES`] linked list.
//! The runner collects entries, builds an [`EntryTree`] for hierarchical
//! display, and executes each benchmark through its [`BenchFn`].

pub mod list;
pub mod meta;
pub(crate) mod tree;

pub use self::list::EntryList;
pub use self::meta::{EntryLocation, EntryMeta};
pub(crate) use self::tree::EntryTree;

use crate::bencher::Bencher;
use crate::config::BenchOptions;

/// Function pointer type for a plain benchmark.
///
/// Takes a shared reference to [`Bencher`]. The higher-ranked lifetime
/// allows the function to work with any `BenchContext` lifetime.
pub type BenchFn = for<'a> fn(&Bencher<'a>);

/// Compile-time entry for a benchmark, generated by `#[pbench::bench]`.
pub struct BenchEntry {
    /// Entry metadata (name, module path, source location).
    pub meta: EntryMeta,

    /// The benchmarking function.
    pub bench_fn: BenchFn,

    /// Optional per-benchmark configuration override.
    ///
    /// When `Some`, the function is called at runtime to produce
    /// [`BenchOptions`] that override group and CLI defaults.
    pub options: Option<fn() -> BenchOptions>,
}

/// Compile-time entry for a benchmark group, generated by
/// `#[pbench::bench_group]`.
///
/// Groups provide hierarchical organisation and options inheritance.
/// A group's options cascade to all child benchmarks during resolution.
pub struct GroupEntry {
    /// Entry metadata (name, module path, source location).
    pub meta: EntryMeta,

    /// Optional group-level configuration override.
    ///
    /// When `Some`, the function is called at runtime to produce
    /// [`BenchOptions`] that apply to all child benchmarks unless
    /// overridden at the individual benchmark level.
    pub options: Option<fn() -> BenchOptions>,
}

/// Compile-time entry for an argument-parameterised benchmark.
///
/// Generated by `#[pbench::bench(args = [...])]`. The runner calls
/// `bench_fn` once per argument value, creating a separate benchmark
/// result for each.
pub struct GenericBenchEntry {
    /// Entry metadata (name, module path, source location).
    pub meta: EntryMeta,

    /// The benchmark function, called once per argument value.
    ///
    /// The `&str` argument is the string representation of the
    /// current argument from [`args`](Self::args).
    pub bench_fn: for<'a> fn(&Bencher<'a>, &str),

    /// Static slice of argument string representations.
    ///
    /// Each element is displayed as part of the benchmark name
    /// (e.g. `"my_bench::1024"`) and passed to `bench_fn`.
    pub args: &'static [&'static str],
}

/// Enum unifying all entry types for the global registration list.
///
/// The proc macro generates one of these variants per `#[pbench::bench]`
/// or `#[pbench::bench_group]` attribute and pushes it into
/// [`BENCH_ENTRIES`] via linker-section init functions.
#[derive(Clone, Copy)]
pub enum AnyBenchEntry {
    /// A plain benchmark entry.
    Bench(&'static BenchEntry),

    /// A benchmark group entry.
    Group(&'static GroupEntry),

    /// An argument-parameterised benchmark entry.
    Generic(&'static GenericBenchEntry),
}

impl AnyBenchEntry {
    /// Access the entry's metadata.
    #[must_use]
    pub const fn meta(&self) -> &EntryMeta {
        match self {
            Self::Bench(e) => &e.meta,
            Self::Group(e) => &e.meta,
            Self::Generic(e) => &e.meta,
        }
    }

    /// The entry's original name (function or module name).
    #[must_use]
    pub const fn raw_name(&self) -> &'static str {
        self.meta().raw_name
    }
}

/// Global list of all registered benchmark entries.
///
/// Entries are pushed into this list at pre-main init time by code
/// generated by `#[pbench::bench]` and `#[pbench::bench_group]`.
/// The runner collects them via [`BENCH_ENTRIES.iter()`](EntryList::iter).
pub static BENCH_ENTRIES: EntryList<AnyBenchEntry> = EntryList::root();
